package com.aftership.models;

import java.util.Date;
import java.util.List;

public class RespTracking{
	 public String id;
	 public Date created_at;
	 public Date updated_at;
	 public Date last_updated_at;
	 public String tracking_number;
	 public String slug;
	 public boolean active;
	 public List<Object> android;
	 public Object custom_fields;
	 public Object customer_name;
	 public int delivery_time;
	 public Object destination_country_iso3;
	 public Object courier_destination_country_iso3;
	 public List<Object> emails;
	 public Object expected_delivery;
	 public List<Object> ios;
	 public Object note;
	 public Object order_id;
	 public Object order_id_path;
	 public Object origin_country_iso3;
	 public int shipment_package_count;
	 public Object shipment_pickup_date;
	 public Object shipment_delivery_date;
	 public Object shipment_type;
	 public Object shipment_weight;
	 public Object shipment_weight_unit;
	 public Object signed_by;
	 public List<Object> smses;
	 public String source;
	 public String tag;
	 public String subtag;
	 public String subtag_message;
	 public String title;
	 public int tracked_count;
	 public Object last_mile_tracking_supported;
	 public Object language;
	 public String unique_token;
	 public List<Object> checkpoints;
	 public List<Object> subscribed_smses;
	 public List<Object> subscribed_emails;
	 public boolean return_to_sender;
	 public Object tracking_account_number;
	 public Object tracking_origin_country;
	 public Object tracking_destination_country;
	 public Object tracking_key;
	 public Object tracking_postal_code;
	 public Object tracking_ship_date;
	 public Object tracking_state;
	 public String order_promised_delivery_date;
	 public String delivery_type;
	 public String pickup_location;
	 public String pickup_note;
	 public String courier_tracking_link;
	 public String courier_redirect_link;
	 public Object first_attempted_at;
	}
